export const itemDropdown = [
  {
    provinsi: "DKI Jakarta",
    wilayah: [
      { label: "Kota Jakarta Pusat", value: "kota-jakarta-pusat" },
      { label: "Kota Jakarta Utara", value: "kota-jakarta-utara" },
      { label: "Kota Jakarta Barat", value: "kota-jakarta-barat" },
      { label: "Kota Jakarta Selatan", value: "kota-jakarta-selatan" },
      { label: "Kota Jakarta Timur", value: "kota-jakarta-timur" },
      { label: "Kabupaten Kepulauan Seribu", value: "kab-kepulauan-seribu" },
    ],
  },
  {
    provinsi: "Jawa Barat",
    wilayah: [
      { label: "Kabupaten Bekasi", value: "kab-bekasi" },
      { label: "Kabupaten Bogor", value: "kab-bogor" },
      { label: "Kabupaten Karawang", value: "kab-karawang" },
      { label: "Kabupaten Purwakarta", value: "kab-purwakarta" },
      { label: "Kabupaten Subang", value: "kab-subang" },
      { label: "Kabupaten Bandung", value: "kab-bandung" },
      { label: "Kabupaten Bandung Barat", value: "kab-bandung-barat" },
      { label: "Kabupaten Sumedang", value: "kab-sumedang" },
      { label: "Kabupaten Garut", value: "kab-garut" },
      { label: "Kabupaten Tasikmalaya", value: "kab-tasikmalaya" },
      { label: "Kabupaten Ciamis", value: "kab-ciamis" },
      { label: "Kabupaten Kuningan", value: "kab-kuningan" },
      { label: "Kabupaten Cirebon", value: "kab-cirebon" },
      { label: "Kabupaten Majalengka", value: "kab-majalengka" },
      { label: "Kabupaten Indramayu", value: "kab-indramayu" },
      { label: "Kabupaten Cianjur", value: "kab-cianjur" },
      { label: "Kabupaten Sukabumi", value: "kab-sukabumi" },
      { label: "Kabupaten Pangandaran", value: "kab-pangandaran" },
      { label: "Kota Bandung", value: "kota-bandung" },
      { label: "Kota Bekasi", value: "kota-bekasi" },
      { label: "Kota Depok", value: "kota-depok" },
      { label: "Kota Bogor", value: "kota-bogor" },
      { label: "Kota Sukabumi", value: "kota-sukabumi" },
      { label: "Kota Cirebon", value: "kota-cirebon" },
      { label: "Kota Tasikmalaya", value: "kota-tasikmalaya" },
      { label: "Kota Cimahi", value: "kota-cimahi" },
      { label: "Kota Banjar", value: "kota-banjar" },
    ],
  },
  {
    provinsi: "Banten",
    wilayah: [
      { label: "Kabupaten Tangerang", value: "kab-tangerang" },
      { label: "Kabupaten Serang", value: "kab-serang" },
      { label: "Kabupaten Lebak", value: "kab-lebak" },
      { label: "Kabupaten Pandeglang", value: "kab-pandeglang" },
      { label: "Kota Tangerang", value: "kota-tangerang" },
      { label: "Kota Tangerang Selatan", value: "kota-tangerang-selatan" },
      { label: "Kota Serang", value: "kota-serang" },
      { label: "Kota Cilegon", value: "kota-cilegon" },
    ],
  },
  {
    provinsi: "Jawa Tengah",
    wilayah: [
      { label: "Kota Semarang", value: "kota-semarang" },
      { label: "Kota Surakarta", value: "kota-surakarta" },
      { label: "Kabupaten Cilacap", value: "kab-cilacap" },
      { label: "Kabupaten Banyumas", value: "kab-banyumas" },
      { label: "Kabupaten Kudus", value: "kab-kudus" },
      { label: "Kabupaten Magelang", value: "kab-magelang" },
      { label: "Kabupaten Brebes", value: "kab-brebes" },
    ],
  },
  {
    provinsi: "Jawa Timur",
    wilayah: [
      { label: "Kota Surabaya", value: "kota-surabaya" },
      { label: "Kota Malang", value: "kota-malang" },
      { label: "Kota Madiun", value: "kota-madiun" },
      { label: "Kabupaten Sidoarjo", value: "kab-sidoarjo" },
      { label: "Kabupaten Gresik", value: "kab-gresik" },
      { label: "Kabupaten Banyuwangi", value: "kab-banyuwangi" },
      { label: "Kabupaten Jember", value: "kab-jember" },
    ],
  },
  {
    provinsi: "Sumatra Utara",
    wilayah: [
      { label: "Kota Medan", value: "kota-medan" },
      { label: "Kota Binjai", value: "kota-binjai" },
      { label: "Kabupaten Deli Serdang", value: "kab-deli-serdang" },
      { label: "Kabupaten Simalungun", value: "kab-simalungun" },
    ],
  },
  {
    provinsi: "Sulawesi Selatan",
    wilayah: [
      { label: "Kota Makassar", value: "kota-makassar" },
      { label: "Kabupaten Gowa", value: "kab-gowa" },
      { label: "Kabupaten Maros", value: "kab-maros" },
      { label: "Kabupaten Bone", value: "kab-bone" },
    ],
  },
] as const;

export const provinceDropdown = [
  { label: "Aceh", value: "aceh" },
  { label: "Sumatra Utara", value: "sumatra-utara" },
  { label: "Sumatra Barat", value: "sumatra-barat" },
  { label: "Riau", value: "riau" },
  { label: "Kepulauan Riau", value: "kepulauan-riau" },
  { label: "Jambi", value: "jambi" },
  { label: "Bengkulu", value: "bengkulu" },
  { label: "Sumatra Selatan", value: "sumatra-selatan" },
  { label: "Kepulauan Bangka Belitung", value: "kepulauan-bangka-belitung" },
  { label: "Lampung", value: "lampung" },
  { label: "DKI Jakarta", value: "dki-jakarta" },
  { label: "Jawa Barat", value: "jawa-barat" },
  { label: "Banten", value: "banten" },
  { label: "Jawa Tengah", value: "jawa-tengah" },
  { label: "DI Yogyakarta", value: "di-yogyakarta" },
  { label: "Jawa Timur", value: "jawa-timur" },
  { label: "Bali", value: "bali" },
  { label: "Nusa Tenggara Barat", value: "nusa-tenggara-barat" },
  { label: "Nusa Tenggara Timur", value: "nusa-tenggara-timur" },
  { label: "Kalimantan Barat", value: "kalimantan-barat" },
  { label: "Kalimantan Tengah", value: "kalimantan-tengah" },
  { label: "Kalimantan Selatan", value: "kalimantan-selatan" },
  { label: "Kalimantan Timur", value: "kalimantan-timur" },
  { label: "Kalimantan Utara", value: "kalimantan-utara" },
  { label: "Sulawesi Utara", value: "sulawesi-utara" },
  { label: "Gorontalo", value: "gorontalo" },
  { label: "Sulawesi Tengah", value: "sulawesi-tengah" },
  { label: "Sulawesi Barat", value: "sulawesi-barat" },
  { label: "Sulawesi Selatan", value: "sulawesi-selatan" },
  { label: "Sulawesi Tenggara", value: "sulawesi-tenggara" },
  { label: "Maluku", value: "maluku" },
  { label: "Maluku Utara", value: "maluku-utara" },
  { label: "Papua Barat", value: "papua-barat" },
  { label: "Papua", value: "papua" },
  { label: "Papua Tengah", value: "papua-tengah" },
  { label: "Papua Pegunungan", value: "papua-pegunungan" },
  { label: "Papua Selatan", value: "papua-selatan" },
  { label: "Papua Barat Daya", value: "papua-barat-daya" },
];
